### ISSUE TITLE
Malicious link

### ISSUE THREAD

**Issue by swanknight** [sinscove/Yuzu-Updater#11]
Whenever I run "Yuzu-Updater" I get a notification from Kaspersky telling me that "Yuzu-Updater" tried to launch a malicious link.
Why is that?

![Screenshot 2022-10-23 101937](https://user-images.githubusercontent.com/46474713/197379523-d7c532b3-ae45-49aa-b911-d83b70cc6570.png)

**Comment by xcloudx01** [comment]
False positive. Go to the link it mentions https://pastebin.com/raw/tc6Pk7rz and it is a simple text file that links to the following link: https://www.mediafire.com/file/ffhy8we0x3vk5d1/

I assume Kaspersky thinks its suspicious because it's opening a Pastebin link.

**Comment by Sin213** [comment]
xcloud got it right
