### ISSUE TITLE
Yuzu-Updater stops at "Retrieved database info"

### ISSUE THREAD

**Issue by tapperp** [sinscove/Yuzu-Updater#12]
The past few days Yuzu Updater 1.5.1 has been unable to get past "Retrieved database info." Anyone else noticing this? Any way to fix it on user end? Or would the app need a coding update?

Here is a screenshot:

![yuzu_updater_issue](https://user-images.githubusercontent.com/27729732/221365336-975db4d2-692f-42ee-a8d7-d68eb3f8a804.png)

Example of log:

> 10:23 AM - INFO - Fetching list of older versions
10:23 AM - INFO - Fetched list of older versions!
10:23 AM - INFO - Retrieved Database Info

It never gets past that point now for me. Tried on 2 different computers, same result.

**Comment by OmniNaut** [comment]
Have same problem here, started a view days ago

**Comment by Sin213** [comment]
Okay same issue here unfortunately. I'll start looking into it, I'll keep you guys posted.

**Comment by Mhytron** [comment]
Same problem here

**Comment by Sin213** [comment]
Pretty amazed the updater went strong for two years without needing updates but the new version fixes this issue. 

https://github.com/sinscove/Yuzu-Updater/releases/tag/v1.5.2
