### ISSUE TITLE
Error with 7zip extraction downloading from Pineapple

### ISSUE THREAD

**Issue by OmniNaut** [sinscove/Yuzu-Updater#18]
I get error file not found while downloading a new Yuzu version from Pineapple.
The file downloads but cannot be extracted.

09:02 - INFO - An error occurred, please check the logs for the issue
09:02 - ERROR - File could not be found.
Parameternaam: filename
09:02 - ERROR -    bij SevenZipNET.SevenZipExtractor..ctor(String filename) in C:\Users\Admin\Documents\Visual Studio 2015\Projects\7z.NET\7z.NET\SevenZipExtractor.cs:regel 48
   bij Yuzu_Updater.MainForm.ArchiveDownloadCompleted(FileDownloadInfo info)

Am I missing a file? Or is this a bug?

Using v1.5.3, Windows 11 22H2

BTW, I don't use "Admin" account. My personal account has admin rights

**Comment by Sin213** [comment]
You might net .NET Framework 4.8.1

https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer

Can you install that and let me know? 

Thank you

**Comment by OmniNaut** [comment]
Sorry I should have mentioned that I already have .Net 4.8.1 installed with Windows update [KB5026515](https://support.microsoft.com/en-au/topic/may-24-2023-kb5026515-cumulative-update-preview-for-net-framework-3-5-and-4-8-1-for-windows-11-version-22h2-9d5e2d61-ddb2-40d3-b90e-f39d9502c5e9)

I tried the web installer, but it does not let me install, because 4.8.1 is already installed on the system

**Comment by Sin213** [comment]
Okay seems like a bug so I'll get back to you.

**Comment by Glumboi** [comment]
I debugged a little bit and could replicate this issue by changing the zip's file name on runtime. 
In other words, it may was the zip file's name that corrupted itself somehow or something like that, I will look further into it and see what exactly it could be, as of now the only clue I have is that the file info (mostly the name) got screwed.

**Comment by Sin213** [comment]
@OmniNaut Alright can you try the new version and let me know, thank you.

**Comment by ThePapaw** [comment]
New version is working for me now, TY

**Comment by OmniNaut** [comment]
I retested with 1.5.4, but it downloaded with Pastebin. Pastebin always works fine for me, so no problems there. 
I hope the next version will download with Pineapple so I can confirm it's solved.

Thanks @sin and @Glumboi
