### ISSUE TITLE
1.5.4 virus warning

### ISSUE THREAD

**Issue by jingshouyan** [sinscove/Yuzu-Updater#20]
# version 1.5.4
The operation could not be completed successfully because the file contained a virus or potentially junk software

![121](https://github.com/sinscove/Yuzu-Updater/assets/7814494/80a9a0f8-242b-4902-984f-86c55287bd49)

**Comment by Sin213** [comment]
False positive, it's because it was embedded with Costura.Fody which Defender hates apparently. Either make an exception or just stick with the old version if you are paranoid and wait for me to manually update. 

https://github.com/sinscove/Yuzu-Updater/pull/17

**Comment by ShizCalev** [comment]
As a note, the last version that doesn't have the false positive (1.5.1) appears to no longer have working downloads.

**Comment by Sin213** [comment]
@ShizCalev The code needed to be updated so it will no longer work. Which antivirus are you using? Feels like I reported the false positive to most of the big ones and they all removed the fake detection.
