### ISSUE TITLE
Updater is not working (Sin hasn't updated yet)

### ISSUE THREAD

**Issue by OmniNaut** [sinscove/Yuzu-Updater#22]
The last couple of days the updater has stopped working. I get this error message.
```
08:27 - INFO - Fetching list of older versions
08:27 - INFO - Fetched list of older versions!
08:27 - INFO - Retrieved Database Info
08:27 - WARNING - De index ligt buiten de matrixgrenzen.
08:27 - INFO - You have the latest version (Sin hasn't updated yet)!
``` 
The warning translates to something like: The index is out side of the matrix borders (or something like that 😉)

**Comment by Sin213** [comment]
Are you using the latest version?

**Comment by KZavi** [comment]
Not the topic starter, but I can confirm I have same issue on version 1.5.4.

**Comment by Sin213** [comment]
Disable Sin Mode, it's not needed anymore. Go into Settings > Experimental > Uncheck Sin Mode 

Close the updater and try again

**Comment by OmniNaut** [comment]
Thanks, that fixed the problem
