### ISSUE TITLE
Please make admin privileges requirement optional

### ISSUE THREAD

**Issue by JimPancakes** [sinscove/Yuzu-Updater#25]
Even if I disable the admin option in settings the app still requires to be run with administrator privileges. Can you please make that optional?

**Comment by JimPancakes** [comment]
Sorry for the confusion. I figured out why this is happening. I'm trying to run it through SMB from a NAS. All my emulators are on there and they work with no issue yet when I try to run this updater from there it says it requires elevation. Otherwise, when running it from my pc, it just works.

I do realize this is a niche case but any ideas on how to fix this? I really need it to not require admin privileges.

**Comment by Sin213** [comment]
Sorry for the late reply Jim but this is no longer being maintained.

-Sin
