### ISSUE TITLE
Wont working

### ISSUE THREAD

**Issue by gitntel** [sinscove/Yuzu-Updater#6]
log error

a System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   a System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a Yuzu_Updater.MainForm.<DownloadAvailableArchivedVersions>d__10.MoveNext()

[updater.log](https://github.com/sinscove/Yuzu-Updater/files/6216940/updater.log)

**Comment by Sin213** [comment]
Nothing to go by that log. I would say to just download again if you haven't gotten it working yet.
