### ISSUE TITLE
update not working

### ISSUE THREAD

**Issue by pogbaxd** [sinscove/Yuzu-Updater#8]
this is my log
 w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w Yuzu_Updater.MainForm.<DownloadVersion>d__12.MoveNext()

**Comment by DocMAX** [comment]
same

**Comment by Desmond404** [comment]
me too

**Comment by gaker19sc** [comment]
yep

**Comment by BetterWaifus** [comment]
same

**Comment by xiaoyvyv** [comment]
#### This version can be used normally
[https://github.com/xiaoyvyv/Yuzu-Early-Access-Updater](https://github.com/xiaoyvyv/Yuzu-Early-Access-Updater)

**Comment by Sin213** [comment]
You need to wait for me to manually update. Sorry about the delay in responding, going to be honest, I completely forgot about needing to maintain the repo.
