### ISSUE TITLE
update randomly not working 

### ISSUE THREAD

**Issue by MisterLotospol** [sinscove/Yuzu-Updater#9]
13:47 - INFO - Fetching list of older versions
13:47 - INFO - Fetched list of older versions!
13:47 - INFO - Retrieved Database Info
13:47 - INFO - Downloading version 2535
This may take a while..
13:47 - INFO - An error occurred, please check the logs for the issue
13:47 - ERROR - A task was canceled.
13:47 - ERROR -    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Yuzu_Updater.MainForm.<DownloadVersion>d__12.MoveNext()

**Comment by xiaoyvyv** [comment]
#### This version can be used normally
[https://github.com/xiaoyvyv/Yuzu-Early-Access-Updater](https://github.com/xiaoyvyv/Yuzu-Early-Access-Updater)
